export const handle_quizIndex = ({commit}) => commit('handle_quizIndex')
export const handle_dequizIndex = ({commit}) => commit('handle_dequizIndex')
export const handle_lookDemand = ({commit}) => commit('handle_lookDemand')
export const detectDevice = ({commit}) => commit('detectDevice')
export const handle_headerBgc = ({commit}) => commit('handle_headerBgc')
export const handle_headerTrans = ({commit}) => commit ('handle_headerTrans')
export const getWebTitle = ({commit}) => commit ('getWebTitle')
export const handle_again = ({commit}) => commit ('handle_again')